routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\KfzDbController;
use App\Http\Controllers\ExportController;
use App\Http\Controllers\RouteController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [KfzDbController::class, 'index'])->name('web.kfzDb.dashboard');
Route::post('/search', [KfzDbController::class, 'search'])->name('web.kzfDb.search');
Route::get('/show/{id}', [KfzDbController::class, 'show'])->name('web.kzfDb.show');

Route::post('/export/{id}', [ExportController::class, 'getExport'])->name('export');

Route::get('/', function () {
    return view('dashboard');
}) -> name('home');

Route::get('/route', function () {
    return view('route');
}) -> name('routenplaner');

Route::get('/input', function () {
    return view('input');
}) -> name('inputkfz');


Route::post('/route', [RouteController::class, 'generateroute']);

Route::resource('KfzDb',KfzDbController::class);

app/Models/KfzDb.php
<?php
namespace App\Models;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class KfzDb extends Model
{
    use HasFactory;
    public $timestamps = false;
    protected $table = "kfz_db";
    protected $fillable = ['kfz_key', 'kfz_kreis', 'kfz_state', 'kfz_city'];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ExportController.php
<?php
namespace App\Http\Controllers;
use App\Http\Export\ExportCsv;
use App\Http\Export\ExportXml;
use App\Http\Export\ExportJson;
use Illuminate\Http\Request;
use App\Models\KfzDb;

class ExportController extends Controller
{
public function getExport(Request $request, $id){
        $kfzDb = KfzDb::where('id', $id)->first();
        switch (request()->get('export_type')) {
            case 'csv':
            $csvExport = new ExportCsv($kfzDb);
            $csvExport->startExport();
            sleep(1);
            $filePath = $csvExport->getFilePath();
            $fileName = $csvExport->getFileName();
            break;
            case 'json':
            $jsonExport = new ExportJson($kfzDb);
            $jsonExport->startExport();
            sleep(1);
            $filePath = $jsonExport->getFilePath();
            $fileName = $jsonExport->getFileName();
            break;
            case 'xml':
            $xmlExport = new ExportXml($kfzDb);
            $xmlExport->startExport();
            sleep(1);
            $filePath = $xmlExport->getFilePath();
            $fileName = $xmlExport->getFileName();
            break;
        }
        return response()->download($filePath, $fileName)->deleteFileAfterSend();
 }
}

app/Http/Controllers/ExportInterface.php
<?php

namespace App\Http\Controllers;
use App\Models\KfzDb;

interface ExportInterface
{
public function startExport(): void;
public function getFilePath(): string;
}

app/Http/Controllers/KfzDbController.php
<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Models\KfzDb;

class KfzDbController extends Controller
{
public function index(){
        return response()->view('dashboard');
    }
public function search(Request $request){
        $data = KfzDb::where('kfz_key', request()->get('kennzeichen_input'))
        ->orWhere('kfz_kreis', request()->get('kennzeichen_input'))
        ->orWhere('kfz_state', request()->get('kennzeichen_input'))
        ->orWhere('kfz_city', request()->get('kennzeichen_input'))
        ->get();
        return response()->view('detail', ['data' => $data]);
    }
public function show(Request $request, $id){
        $kfz = KfzDb::find($id);
        return response()->view('summary', ['kfz' => $kfz]);
    }
    public function create()
    {
        return view('KfzDb.KfzDb');
    }
    public function store(Request $request)
    {
     $input = $request ->all();
     KfzDb::create($input);
     return redirect()->back();
    }

}

app/Http/Controllers/RouteController.php
<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;

class RouteController extends Controller
{
public function generateroute(Request $request){
        $start=request()->get('startpunkt_input');
        $ziel=request()->get('zielpunkt_input');
        $url='https://www.google.de/maps/dir/'.$start.'/'.$ziel;
        return Redirect::to($url);
    }
}

resources/views/dashboard.blade.php
@extends('main')

@section('content')
    <div class="container-fluid mt-5">
        <div class="card">
            <div class="card-header">
                <h1>Kennzeichen – Abfrage</h1>
            </div>
            <form action="/search" method="POST">
                @csrf
                <div class="card-body">
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="kennzeichen_input">Kennzeichen Eingeben</span>
                        <input type="text" class="form-control" placeholder="z.B: 'GG', 'Hessen', 'Groß-Gerau' " name="kennzeichen_input" aria-label="Username" aria-describedby="kennzeichen_input">
                    </div>
                    <div class="d-grid gap-2">
                        <button class="btn btn-primary btn-lg" type="submit">Suchen</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/detail.blade.php
@extends('main')

@section('content')
<div class="container-fluid mt-5">
    <div class="card">
        <div class="card-header">
            <h1>Kennzeichen - Liste:</h1>
        </div>
        <div class="card-body">
            <div class="list-group">
                @foreach ($data as $dataObject)
                    <a href="/show/{{$dataObject->id}}" class="list-group-item list-group-item-action" aria-current="true">
                        {{$loop->index +1}}. Kennzeichenkürzel: {{$dataObject->kfz_key ?? 'Kein Datensatz vorhanden'}}, Bundesland: {{$dataObject->kfz_state ?? 'Kein Datensatz vorhanden'}}, Kreisstadt: {{$dataObject->kfz_city ?? 'Kein Datensatz vorhanden'}}, Kreis: {{$dataObject->kfz_kreis ?? 'Kein Datensatz vorhanden'}}
                    </a>
                @endforeach
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/input.blade.php
@extends('main')
@section('content')
<div class="container-fluid mt-5">
    <div class="card">
        <div class="card-header">
            <h1>Kennzeichen – Eingabe</h1>
        </div>
<form action="{{route('KfzDb.store')}}" method="post">
    @csrf
    <div class="card-body">
        <div class="input-group mb-3">
            <span class="input-group-text" id="kfz_key">Kennzeichen</span>
 <input type="text" name="kfz_key" id="kfz_key" class="form-control" placeholder="Enter Kennzeichen">
 </div>
 <div class="input-group mb-3">
    <span class="input-group-text" id="kfz_state">Bundesland</span>
 <input type="text" name="kfz_state" id="kfz_state" class="form-control" placeholder="Enter Bundesland" aria-label="Username" aria-describedby="bundesland">
 </div>
 <div class="input-group mb-3">
    <span class="input-group-text" id="kfz_kreis">Kreis</span>
 <input type="text" name="kfz_kreis" id="kfz_kreis" class="form-control" placeholder="Enter Kreis">
 </div>
 <div class="input-group mb-3">
    <span class="input-group-text" id="kfz_city">Stadt</span>
 <input type="text" name="kfz_city" id="kfz_city" class="form-control" placeholder="Enter Stadt">
 </div>
 </div>
 </div>
 <div class="d-grid gap-2">
 <button type="submit" class="btn btn-primary">Hinzufügen</button>
 </div>
</form>
</div>
</div>
@endsection

resources/views/route.blade.php
@extends('main')

@section('content')
    <div class="container-fluid mt-5">
        <div class="card">
            <div class="card-header">
                <h1>Routenplaner</h1>
            </div>
            <form action="/route" method="POST">
                @csrf
                <div class="card-body">
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="startpunkt_input">Startpunkt</span>
                        <input type="text" class="form-control" placeholder="z.B: 'Groß-Gerau' " name="startpunkt_input" aria-label="Username" aria-describedby="startpunkt_input">
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="zielpunkt_input">Zielpunkt</span>
                        <input type="text" class="form-control" placeholder="z.B: 'Darmstadt' " name="zielpunkt_input" aria-label="Username" aria-describedby="zielpunkt_input">
                    </div>
                    <div class="d-grid gap-2">
                        <button class="btn btn-primary btn-lg" type="submit">Route berechnen</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/summary.blade.php
@extends('main')

@section('content')
<div class="container-fluid mt-5">
    <div class="card">
        <div class="card-header">
            <h1>Kennzeichen Ausgabe:</h1>
        </div>
      <div class="card-body">
      <ul class="list-group">
            <li class="list-group-item"><p>Kreis: {{$kfz->kfz_kreis ?? 'Kein Datensatz vorhanden'}}</p></li>
            <li class="list-group-item"><p>Bundesland: {{$kfz->kfz_state ?? 'Kein Datensatz vorhanden'}}</p></li>
            <li class="list-group-item"><p>Stadt: {{$kfz->kfz_city ?? 'Kein Datensatz vorhanden'}}</p></li>
            <li class="list-group-item"> <p>Kennzeichen: {{$kfz->kfz_key ?? 'Kein Datensatz vorhanden'}}</p></li>
            </ul>
        </div>
        <div class="list-group">
            <a href="https://de.wikipedia.org/wiki/{{$kfz->kfz_city}}" class="list-group-item list-group-item-action list-group-item-primary"><center>Wikipedia Link</center></a>
            <a href="https://www.google.de/maps/place/{{$kfz->kfz_city}}" class="list-group-item list-group-item-action list-group-item-primary"><center>Google Maps Link</center></a>
        </div>
        <br></br>
        <div class="d-flex card-footer justify-content-between">
            <form action="/export/{{$kfz->id}}" method="POST">
                @csrf
                <input type="hidden" name="export_type" value="xml">
                <button class="btn btn-primary" type="submit">Xml Datei</button>
            </form>
            <form action="/export/{{$kfz->id}}" method="POST">
                @csrf
                <input type="hidden" name="export_type" value="csv">
                <button class="btn btn-primary" type="submit">Csv Datei</button>
            </form>
            <form action="/export/{{$kfz->id}}" method="POST">
                @csrf
                <input type="hidden" name="export_type" value="json">
                <button class="btn btn-primary" type="submit">Json Datei</button>
        </div>
    </div>
</div>
@endsection